platform :ios, ‘9.0’
target "swiftTest" do
use_frameworks!
pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
end
